-- ENUM
CREATE TYPE "item_type" AS ENUM (
  'MEDICINE',
  'MEDICAL_TOOL'
);

CREATE TYPE "invoice_status" AS ENUM (
  'UNPAID',
  'PARTIAL',
  'PAID'
);

CREATE TYPE "payment_method" AS ENUM (
  'CASH',
  'CARD',
  'MEMBER_WALLET'
);

CREATE TYPE "unit_type" AS ENUM (
  'U',
  'CC',
  'PIECE'
);

CREATE TYPE "stock_movement_type" AS ENUM (
  'OPENING_BALANCE',
  'PURCHASE_IN',
  'USE_FOR_PROMOTION',
  'USE_FOR_TREATMENT',
  'WASTE',
  'ADJUST'
);


CREATE TYPE "promotion_benefit_type" AS ENUM (
  'PERCENT_DISCOUNT',
  'AMOUNT_DISCOUNT',
  'FREE_ITEM',
  'WALLET_CREDIT'
);

CREATE TYPE "promotion_target_scope" AS ENUM (
  'INVOICE_TOTAL',
  'LINE_ITEM'
);

CREATE TYPE "promotion_rule_type" AS ENUM (
  'MIN_SPEND',
  'HAS_ITEM',
  'MIN_QTY_ITEM',
  'NEW_CUSTOMER_ONLY',
  'MIN_WALLET_TOPUP'
);

CREATE TYPE "promotion_rule_op" AS ENUM (
  'EQ',
  'GTE',
  'LTE'
);

CREATE TYPE "invoice_promo_line_type" AS ENUM (
  'DISCOUNT',
  'FREE_ITEM',
  'WALLET_CREDIT'
);

CREATE TYPE "chat_role" AS ENUM (
  'USER',
  'SYSTEM'
);

-- TABLES
-- A chat session/conversation
CREATE TABLE conversations (
  conversation_id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title         TEXT,
  created_at    timestamp DEFAULT (now()),
  updated_at    timestamp DEFAULT (now())
);

-- One message per turn (user/system)
CREATE TABLE messages (
  message_id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint NOT NULL REFERENCES conversations(conversation_id) ON DELETE CASCADE,
  role            chat_role NOT NULL,
  content         TEXT NOT NULL,
  token_count     INT,
  model           TEXT,
  created_at      timestamp DEFAULT (now())
);

CREATE TABLE "customer" (
  "customer_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_code" varchar(50) UNIQUE,
  "full_name" varchar,
  "nickname" varchar,
  "phone" varchar(10),
  "date_of_birth" date,
  "member_wallet_remain" decimal(10,2)
);

CREATE TABLE "supplier" (
  "supplier_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "supplier_code" varchar(50) UNIQUE,
  "description" varchar,
  "name" varchar,
  "phone" varchar(10),
  "address" varchar
);

CREATE TABLE "item_group" (
  "item_group_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_code" varchar(50) UNIQUE,
  "name" varchar,
  "item_type" item_type,
  "unit" unit_type,
  "current_qty" decimal(12,2) DEFAULT 0,
  "description" varchar
);

CREATE TABLE "daily_stock" (
  "stock_date" date,
  "item_group_id" bigint REFERENCES "item_group" ("item_group_id") ON DELETE CASCADE,
  "qty" decimal(12,2) NOT NULL DEFAULT 0,
  PRIMARY KEY ("stock_date", "item_group_id")
);

CREATE TABLE "item_catalog" (
  "item_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "item_group_id" bigint REFERENCES "item_group" ("item_group_id") ON DELETE CASCADE,
  "sku" varchar(50) UNIQUE,
  "name" varchar,
  "variant_name" varchar,
  "sell_price" decimal(10,2),
  "unit" unit_type,
  "unit_per_package" decimal(10,2),
  "tracking_mode" tracking_mode,
  "restock_threshlod" decimal(10,2),
  "description" varchar
);

CREATE TABLE "promotion" (
  "promotion_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE,
  "name" varchar,
  "description" varchar,
  "is_stackable" boolean DEFAULT false,
  "start_at" timestamp,
  "end_at" timestamp,
  "is_active" boolean DEFAULT true,
  "max_redemptions_total" int,
  "max_redemptions_per_customer" int,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "purchase_invoice" (
  "purchase_invoice_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "purchase_no" varchar(50) UNIQUE,
  "supplier_id" bigint REFERENCES "supplier" ("supplier_id") ON DELETE CASCADE,
  "issue_date" datetime,
  "total_amount" decimal(10,2)
);

CREATE TABLE "sell_invoice" (
  "sell_invoice_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "invoice_no" varchar(50) UNIQUE,
  "customer_id" bigint REFERENCES "customer" ("customer_id") ON DELETE CASCADE,
  "issued_at" datetime,
  "total_amount" decimal(10,2),
  "discount_amount" decimal(10,2),
  "final_amount" decimal(10,2),
  "status" invoice_status
);

CREATE TABLE "wallet_movement" (
  "created_at" timestamp DEFAULT (now()),
  "customer_id" bigint REFERENCES "customer" ("customer_id") ON DELETE CASCADE,
  "amount" decimal(10,2),
  PRIMARY KEY ("created_at", "customer_id")
);

CREATE TABLE "sell_invoice_item" (
  "item_id" bigint REFERENCES "item_catalog" ("item_id") ON DELETE CASCADE,
  "sell_invoice_id" bigint REFERENCES "sell_invoice" ("sell_invoice_id") ON DELETE CASCADE,
  "description" varchar,
  "qty" int,
  "total_price" decimal(10,2),
  PRIMARY KEY ("item_id", "sell_invoice_id")
);

CREATE TABLE "payment" (
  "payment_time" timestamp DEFAULT (now()),
  "sell_invoice_id" bigint REFERENCES "sell_invoice" ("sell_invoice_id") ON DELETE CASCADE,
  "receipt_no" varchar(50) UNIQUE,
  "method" payment_method,
  "amount_customer_paid" decimal(10,2),
  "card_fee" decimal(10,2),
  "clinic_amount" decimal(10,2),
  PRIMARY KEY ("payment_time", "sell_invoice_id")
);

CREATE TABLE "purchase_invoice_item" (
  "purchase_invoice_id" bigint REFERENCES "purchase_invoice" ("purchase_invoice_id") ON DELETE CASCADE,
  "item_id" bigint REFERENCES "item_catalog" ("item_id") ON DELETE CASCADE,
  "qty" int,
  "purchase_price_per_unit" decimal(10,2)
  PRIMARY KEY ("item_id", "purchase_invoice_id")
);

CREATE TABLE "stock_movement" (
  "created_at" timestamp DEFAULT (now()),
  "item_id" bigint REFERENCES "item_catalog" ("item_id") ON DELETE CASCADE,
  "movement_type" stock_movement_type,
  "qty" int,
  "sell_invoice_id" bigint REFERENCES "sell_invoice" ("sell_invoice_id") ON DELETE CASCADE,
  "purchase_invoice_id" bigint REFERENCES "purchase_invoice" ("purchase_invoice_id") ON DELETE CASCADE,
  "expired_at" timestamp,
  PRIMARY KEY ("created_at", "item_id")
);

CREATE TABLE "treatment_recipe" (
  "treatment_id" bigint,
  "item_id" bigint REFERENCES "item_catalog" ("item_id") ON DELETE CASCADE,
  "qty_per_session" decimal(10,2),
  "sell_price" decimal(10,2),
  "image_obj_key" varchar,
  "description" varchar,
  PRIMARY KEY ("treatment_id", "item_id")
);

CREATE TABLE "promotion_benefit" (
  "promotion_benefit_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "promotion_id" bigint NOT NULL REFERENCES "promotion" ("promotion_id") ON DELETE CASCADE,
  "benefit_type" promotion_benefit_type,
  "target_scope" promotion_target_scope,
  "target_item_id" bigint,
  "value_percent" decimal(10,2),
  "value_amount" decimal(10,2),
  "free_item_id" bigint,
  "free_qty_base_unit" decimal(10,2)
);

CREATE TABLE "promotion_condition_group" (
  "condition_group_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "promotion_id" bigint NOT NULL REFERENCES "promotion" ("promotion_id") ON DELETE CASCADE,
  "sort_order" int NOT NULL DEFAULT 1
);

CREATE TABLE "promotion_condition_rule" (
  "condition_rule_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "condition_group_id" bigint NOT NULL REFERENCES "promotion_condition_group" ("condition_group_id") ON DELETE CASCADE,
  "rule_type" promotion_rule_type NOT NULL,
  "op" promotion_rule_op NOT NULL,
  "amount_value" decimal(10,2),
  "item_id" bigint,
  "qty_base_unit" decimal(10,2),
  "text_value" varchar(100)
);

CREATE TABLE "promotion_redemption" (
  "promotion_redemption_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "promotion_id" bigint NOT NULL REFERENCES "promotion" ("promotion_id") ON DELETE CASCADE,
  "sell_invoice_id" bigint NOT NULL REFERENCES "sell_invoice" ("sell_invoice_id") ON DELETE CASCADE,
  "customer_id" bigint NOT NULL REFERENCES "customer" ("customer_id") ON DELETE CASCADE,
  "coupon_code_used" varchar(50),
  "discount_total" decimal(10,2) DEFAULT 0,
  "wallet_credit_total" decimal(10,2) DEFAULT 0,
  "redeemed_at" timestamp DEFAULT (now())
);

CREATE TABLE "sell_invoice_promotion_line" (
  "sell_invoice_promotion_line_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sell_invoice_id" bigint NOT NULL REFERENCES "sell_invoice" ("sell_invoice_id") ON DELETE CASCADE,
  "sell_invoice_item_id" bigint,
  "promotion_redemption_id" bigint REFERENCES "promotion_redemption" ("promotion_redemption_id") ON DELETE CASCADE,
  "promotion_id" bigint NOT NULL REFERENCES "promotion" ("promotion_id") ON DELETE CASCADE,
  "promotion_benefit_id" bigint REFERENCES "promotion_benefit" ("promotion_benefit_id") ON DELETE CASCADE,
  "line_type" invoice_promo_line_type NOT NULL,
  "amount" decimal(10,2) NOT NULL DEFAULT 0,
  "free_item_id" bigint,
  "free_qty_base_unit" decimal(10,2),
  "stock_movement_id" bigint,
  "wallet_credit_amount" decimal(10,2),
  "wallet_movement_id" bigint,
  "description" varchar(255),
  "created_at" timestamp
);
