-- ==========================================
-- REFINE HAUS CLINIC - AI CHATBOT SETUP
-- Vector Database Configuration for RAG
-- ==========================================

-- Enable pgvector extension for semantic search
CREATE EXTENSION IF NOT EXISTS vector;

-- ==========================================
-- EMBEDDINGS TABLE
-- ==========================================
-- Stores vector embeddings for semantic search (RAG)
-- Used for unstructured queries like "suggest skincare promotion"

CREATE TABLE IF NOT EXISTS chat_embeddings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL,
  embedding vector(1536), -- OpenAI text-embedding-ada-002 produces 1536 dimensions
  metadata JSONB,
  created_at timestamp DEFAULT now()
);

-- Fast similarity search index using IVFFlat algorithm
-- vector_cosine_ops: Uses cosine distance (1 - cosine similarity)
CREATE INDEX IF NOT EXISTS chat_embeddings_embedding_idx
ON chat_embeddings USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- Index for metadata queries (e.g., filter by document type, date)
CREATE INDEX IF NOT EXISTS chat_embeddings_metadata_idx
ON chat_embeddings USING gin (metadata);

-- ==========================================
-- HELPER FUNCTIONS
-- ==========================================

-- Function to search similar embeddings (for RAG retrieval)
CREATE OR REPLACE FUNCTION search_embeddings(
  query_embedding vector(1536),
  match_threshold float DEFAULT 0.7,
  match_count int DEFAULT 5
)
RETURNS TABLE (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    chat_embeddings.id,
    chat_embeddings.content,
    chat_embeddings.metadata,
    1 - (chat_embeddings.embedding <=> query_embedding) as similarity
  FROM chat_embeddings
  WHERE 1 - (chat_embeddings.embedding <=> query_embedding) > match_threshold
  ORDER BY chat_embeddings.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- ==========================================
-- SEED SAMPLE EMBEDDINGS (OPTIONAL)
-- ==========================================
-- This helps the AI understand clinic context
-- You can generate real embeddings later via Python script

COMMENT ON TABLE chat_embeddings IS 'Stores vector embeddings for semantic search in AI chatbot';
COMMENT ON COLUMN chat_embeddings.embedding IS 'OpenAI ada-002 embedding (1536 dimensions)';
COMMENT ON COLUMN chat_embeddings.metadata IS 'Additional context: {type, category, date, etc.}';
